### ISSUE TITLE
Incomplete set of oxidation states.

### ISSUE THREAD

**Issue by pkienzle** [pkienzle/periodictable#15]
Missing valid oxidation states for some elements.  E. g., 

   periodictable.formula('H{-}')

raises a ValueError claiming -1 is not a valid charge for H, even though this is the hydride anion.
Other physically sound examples raises this exception, e.g. He{+}.

Wikipedia has a list:

```
https://en.wikipedia.org/wiki/List_of_oxidation_states_of_the_elements
```

This still doesn't include He{+}, but it has many more of them than the existing code.  It also distinguishes common and uncommon, which the existing code does not.

**Comment by bjodah** [comment]
Just came across another example, one cannot enter the thiocyanate ion using `periodictable.formula`:

```
>>> import periodictable as pt
>>> pt.formula('SCN{-}')
ValueError: -1 is not a valid charge for N
```

same goes for any permutation of order (-1 not valid for any of C, N, S)

**Comment by pkienzle** [comment]
I added the list of oxidation states on the wikipedia list of oxidation states, and including He+ and Hg4+ (doi:10.1002/anie.200703710).
