### ISSUE TITLE
unify `__getitem__`

### ISSUE THREAD

**Issue by CJ-Wright** [pkienzle/periodictable#20]
It might be nice if `__getitem__` took in element symbols/names in addition to numbers.

**Comment by pkienzle** [comment]
The trivial implementation, extending the dictionary of elements to contain symbols and names, would break the table iterator.  Conceptually, having more keys "in" the dictionary then are returned by iterating through it is unexpected (and therefore bad).

The type signature would be ugly, which is generally a bad sign.

The interface already provides table.Fe, table.symbol('Fe') and getattr(table, 'Fe'),  so table['Fe'] is even more redundant.  This breaks the Zen of Python:  *There should be one-- and preferably only one --obvious way to do it.*

So, how compelling are the arguments to add it?
