### ISSUE TITLE
can't import periodictable in setup.py using pip

### ISSUE THREAD

**Issue by bmaranville** [pkienzle/periodictable#27]
There is a problem installing periodictable using pip with embedded python - it seems to be unable to run the "import periodictable" statement in setup.py
The error messag is:
File "C:\Users\bbm\AppData\Local\Temp\2\pip-req-build-lu4txyig\setup.py", line 8, in <module>
        import periodictable
    ModuleNotFoundError: No module named 'periodictable'

**Comment by pkienzle** [comment]
Should be fixed in 1.5.1
