### ISSUE TITLE
Support for nose2

### ISSUE THREAD

**Issue by sagitter** [pkienzle/periodictable#31]
Hi all.

Since `python-nose` will be [deprecated](https://fedoraproject.org/wiki/Changes/DeprecateNose) soon on Fedora, i need that `periodictable` is compatible with [nose2](https://docs.nose2.io/en/latest/) to be included in the official repositories.

Please, evaluate this possibility.

**Comment by pkienzle** [comment]
or pytest?

**Comment by nonamedotc** [comment]
pytest would work too I believe.

**Comment by pkienzle** [comment]
I've commit changes to the repo, including a license file and a switch to pytest.  Please let me know if this meets your needs and I'll create a new release.
