### ISSUE TITLE
Support for X-ray emission energies (EDX) 

### ISSUE THREAD

**Issue by FilipDominec** [pkienzle/periodictable#32]
While I find it an excellent idea to gather all chemical element information in a python module, from the current documentation it is really hard to tell what quantities are available and what not. Maybe an example on the title page would help. 

In particular, I was searching for the K-, L- and M- line energies for EDX spectra analysis. I guess they are not in the module yet, but they were published elsewhere. Should I put them into a table and make a PR?

**Comment by pkienzle** [comment]
In principle yes. I already have Kα and Kβ1 lines computed from the NIST [X-ray transition energies database](https://www.nist.gov/pml/x-ray-transition-energies-database) in the data [here](https://github.com/pkienzle/periodictable/blob/1c2cecea6a6d4019167dcd6ee231431b11af5480/periodictable/xsf.py#L523-L627). I don't mind adding more as long as the database isn't overly large, and we have a license to include them. What dataset do you have in mind?

**Comment by FilipDominec** [comment]
To my regret, reading available documentation and the source code I had no clue to open ```xsf.py``` and search for a string called ```spectral_lines_data``` on line 523 there. To get my work done, downloading the NIST data [1] has proven to be the most straightforward way. I consider this issue to be closed. Thank you for your answer, anyway.

[1]: https://physics.nist.gov/PhysRefData/XrayTrans/Html/search.html
