### ISSUE TITLE
Add three-letter amino acid codes to FASTA module

### ISSUE THREAD

**Issue by hoogerheide** [pkienzle/periodictable#46]
Amino acids have a single letter code such as that used by FASTA, but other file formats in which biomolecular information is stored (e.g. PDBs) use a three letter code, e.g. 'ALA' for alanine or 'TRP' for tryptophan. Support for the three letter codes would be a useful feature though not specifically FASTA related.

Here's a complete mapping:
```
dict({'A': 'ALA', 'R': 'ARG', 'N': 'ASN', 'D':'ASP', 'C':'CYS', 'E':'GLU', 'Q':'GLN', 'G':'GLY', 'H':'HIS',
               'I': 'ILE', 'L':'LEU', 'K':'LYS', 'M':'MET', 'F': 'PHE', 'P': 'PRO', 'S':'SER', 'T':'THR', 'Y':'TYR',
                'V': 'VAL', 'W': 'TRP'})
```

**Comment by pkienzle** [comment]
I don't mind having the definition in fasta.py if it is generally useful for computing SLD but I can't judge the utility.

Are these codes used outside of PDB? Would it make more sense to define this in a PDB reader?

**Comment by hoogerheide** [comment]
I typically use the MDAnalysis package to read in PDB files. It has a utility that does the three letter to 1 letter conversion: https://docs.mdanalysis.org/1.1.1/documentation_pages/lib/util.html#MDAnalysis.lib.util.convert_aa_code

It would also be a perfectly respectable design choice to ask users to parse their own PDB files and use a similar utility to produce one letter codes.

**Comment by pkienzle** [comment]
If the only thing we are using is the FASTA sequence then I'm happy to leave the conversion to an external reader.

You could make an argument for including a routine for counting exposed labile H. Although it would be better to include this in the PDB reader which knows its own data structures, it would also have a natural home in the bio sld calculator.

Would it be useful to add a PDB parser to the online activation calculator? Then you could use the url of a PDB file in place of the formula and have it compute the SLD. There is already a [PDB reader in js](https://github.com/biasmv/pv), so it may not be too hard.
