### ISSUE TITLE
`eval` is present within code base.

### ISSUE THREAD

**Issue by KOLANICH** [pkienzle/periodictable#52]
https://github.com/pkienzle/periodictable/blob/4fb8068cc94a96704646e14ef2aebf939697e164/periodictable/magnetic_ff.py#L132-L135

While it claims it is secure, it still needs to be eliminated. Noone can guarantee it is secure. Data must be data, not code.

The code that is `eval`ed looks like boilerplate one. This means the boilerplate can be extracted and executed as a function, and the data can be kept as just data. It would be more secure: there will be guarantees that changes within data won't cause code execution. And to make the audit easier, the data should be in separate files, not in source code files.

**Comment by pkienzle** [comment]
Agree that it makes auditing easier if there is no eval.

Disagree that removing the eval in this case improves security. The data is coming from the file itself. If you are compromised to the point that the data in the file can be modified then the code in the file could be modified by the same mechanism.

The boundary between code and data is always going to be fuzzy. Is math.pi data? How about constants.electron_radius or fasta.AMINO_ACID_CODES?

I kept the data in its original form to make it easier to cross-check against original sources and pull in updates. For convenience I embed it in the source documents.

It would be reasonable to split the original sources and source parsers into a separate support directory and have them generate a "compiled" form that could be used in the periodictable package. This would reduce package startup time, and maybe memory usage (large tables like the xray scattering factors could live in a sqlite database for example [see #13]; smaller datasets could live in json files).

There is a question of when this build step should be run. With the trend toward replacing setup.py with a declarative structure we should be storing the compiled data directly in the repo. This also preserves the convenience of pointing python path to the repo and having the package available with no build step required. However, storing generated files in the repo gets awkward, especially if it is a large binary blob, like a single sqlite database containing tables for all the element properties. I don't have a good answer for this.

I'll leave this ticket open as a reminder that removing eval makes it easier to audit and that we ought to be separating the work that can be done in advance, but I have no plans to address it myself. If you make a PR then keep it simple, just addressing the magnetic_ff.py datatable. Don't do too much work before we discuss it further.

**Comment by KOLANICH** [comment]
> Disagree that removing the eval in this case improves security.

Making audit eaeier improves security by lowering chance malicious changes being unnoticed.

>The boundary between code and data is always going to be fuzzy. Is math.pi data? How about constants.electron_radius or fasta.AMINO_ACID_CODES?

I aggree. In the case of modules made of constants, they are likely autogenerated.

>It would be reasonable to split the original sources and source parsers into a separate support directory

Or maybe in a separate data-only package....

>and have them generate a "compiled" form that could be used in the periodictable package. This would reduce package startup time, and maybe memory usage (large tables like the xray scattering factors could live in a sqlite database for example [see #13]; smaller datasets could live in json files).

Generating SQLite databases and ship their files can be a security issue. The official SQLite impl is not supposed to be used against untrusted data files and/or untrusted SQL queries. There were quite some CVEs about such usage the most well-known one were the ones in Chromium Web SQL technology.

Sometimes key-value storages can be put into an on-disk hashtable usable throuth a memmap. For example `mo` translation files of `libintl` are such a format (maps a byte string to a byte string), but the most impls (including the one in Python stdlib) don't use the optional hashtable component of the file, relying on a sorted list mandatory component. About memmapping ... `mmap.mmap` mimics the interface of `io.IOBase`, so one can often use it where results of `open` are used. But it doesn't mean the underlying impl can benefit from mmaping in terms of memory consumption reduction, for example it can parse whole file and cache results into memory.

**Comment by KOLANICH** [comment]
If you want to play with `mo` format, https://github.com/KOLANICH-libs/transformerz.py/blob/master/transformerz/serialization/libintl.py can be useful.
