### ISSUE TITLE
Nucleon/mass number

### ISSUE THREAD

**Issue by keg504** [pkienzle/periodictable#53]
I'm not quite sure if I've missed this in the documentation, but I haven't been able to find data for nucleon number. This would be really useful for certain calculations such as ion pressure in astrophysics.

**Comment by pkienzle** [comment]
Each isotope has `iso.number` = p+n and `iso.element.number` = p. Does that do what you need?

**Comment by keg504** [comment]
That would work, I don't think I understand the syntax though. This is what I write:
```
import periodictable as pt
for isotope in pt.H:
    print(isotope.number)
```
And this is what I get:
>\> python test.py
1
1
1
1
1
1

**Comment by pkienzle** [comment]
That would be because the attribute you need is `isotope` not `number`.  The `number` attribute delegates to the base element.
```
>>> print([iso.isotope for iso in pt.H])
[1, 2, 3, 4, 5, 6]
```
Sorry for the confusion!

**Comment by keg504** [comment]
Thanks, it works now! That works. It would be nice to have the nucleon number as an easy to access variable like ```pt.H.nucleon``` of the most common isotope, but I do understand it would come with issues when it comes to synthetic and unstable elements.
I'll go ahead and close this issue now.
