### ISSUE TITLE
Oxygen Incoherent Scattering Cross Section set as 0?

### ISSUE THREAD

**Issue by CosmicPidgeon** [pkienzle/periodictable#63]
According to [NIST scattering resource](https://www.ncnr.nist.gov/resources/n-lengths/) the incoherent cross section for oxygen (natural abundance) and fluorine are the same. I was therefore wondering why oxygen (natural abundance) is given as 0 when doing `periodictable.elements.symbol('O').neutron.incoherent` but the same for 'F' gives 0.0008 as expected.

**Comment by pkienzle** [comment]
Both Sears (Tables of crystallography)[1] and Rauch (ATI tables)[2] have O incoherent as 0.000(8). I reported the discrepancy to the author of the above page.

[1] https://it.iucr.org/Cb/ch4o4v0001/sec4o4o4/
[2] http://www.ati.ac.at/~neutropt/scattering/Scattering_lengths_table_20010419.pdf
