### ISSUE TITLE
Add half-life information for isotopes

### ISSUE THREAD

**Issue by pkienzle** [pkienzle/periodictable#7]

**Comment by jrsmith3** [comment]
Is there an open data set for this?

**Comment by pkienzle** [comment]
Here are some:

    http://www.nist.gov/pml/data/halflife-ascii.cfm
    http://www.nist.gov/public_affairs/disclaimer.cfm

**Comment by pkienzle** [comment]
More complete data is available at the national nuclear data center:

    http://www.nndc.bnl.gov/

The data is freely distributed, but I don't know if it can be redistributed.

**Comment by jrsmith3** [comment]
Thanks for the URLs! Shouldn't the data be freely redistributable since its coming from a national lab? I thought all US gov data was public domain.

**Comment by pkienzle** [comment]
The Brookhaven disclaimer says they aren't responsible for third party
copyright claims:

    ...or represents that its use would not infringe privately owned
rights...

http://www.bnl.gov/bnlweb/security-notice.php

**Comment by pkienzle** [comment]
Closing in favour of #77
