### ISSUE TITLE
Clarification on the license

### ISSUE THREAD

**Issue by mrakitin** [pkienzle/periodictable#85]
Dear developers,

Could you please clarify the type of the license used for the project, according to https://spdx.org/licenses/? There are a few kinds of public domain licenses there. A portion of the current license is pretty close to the BSD-3-Clause:
https://github.com/pkienzle/periodictable/blob/b36d7bf9def086c1e5a7a62d29e25d8e79f5a8f2/LICENSE.txt#L19-L28

This question was raised during a conda-forge feedstock update, via https://github.com/conda-forge/periodictable-feedstock/pull/11.

Thank you!

**Comment by pkienzle** [comment]
BSD-3-Clause

Most of the code has no restrictions, but conda-forge will be distributing the whole package so needs to specify the most restrictive license.
