### ISSUE TITLE
Syntax for multilayers 

### ISSUE THREAD

**Issue by bpedersen2** [pkienzle/periodictable#9]
From our reflectometry users we have a request for adding support for their "standard" description of samples. 
`GaAs Substrat with [Fe 15nm / Cr 1.1nm]x10`

I am thinking about extending the Mixture syntax for that purpose:

`$<area>(15#(µ|nm) Fe@density // 1.1#(µ|nm) Cr@density)*10 // GaAs` 

So using `#` as the layer mode indicator. The mass per layer is calulated from the density(tabulated value if not specified) and area \* thickness. 

Do you think this is reasonable? Once finished I will provide pull request.

Björn

**Comment by pkienzle** [comment]
Feature added, but still needs documentation before closing the issue

**Comment by bpedersen2** [comment]
https://github.com/pkienzle/periodictable/blob/master/doc/sphinx/guide/formula_grammar.rst seems to be there?

**Comment by pkienzle** [comment]
Okay, I'll close the ticket.   Thanks.
